In [1]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.9.0-py3-none-any.whl.metadata (15 kB)
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.19.1-py3-none-any.whl.metadata (7.3 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.12.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.51)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna) (1.1.3)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.16.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.5.3)
Downloading optuna-4.9.0-py3-none-any.whl (425 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 425.6/425.6 kB 6.5 MB/s eta 0:00:00
Downloading alembic-1.19.1-py3-none-any.whl (265 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 265.9/265.9 kB 14.1 MB/s eta 0:00:00
Downloading colorlog-6.12.0-py3-none-any.whl (12 kB)
Installing collected packages: colorlog, alembic, optuna
Successfully installed alembic-1.19.1 colorlog-6.12.0 optuna-4.9.0

In [2]:
# Import necessary libraries
import optuna
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load the Pima Indian Diabetes dataset from sklearn
# Note: Scikit-learn's built-in 'load_diabetes' is a regression dataset.
# We will load the actual diabetes dataset from an external source
import pandas as pd

# Load the Pima Indian Diabetes dataset (from UCI repository)
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']

# Load the dataset
df = pd.read_csv(url, names=columns)

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [3]:
import numpy as np

# Replace zero values with NaN in columns where zero is not a valid value
cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0, np.nan)

# Impute the missing values with the mean of the respective column
df.fillna(df.mean(), inplace=True)

# Check if there are any remaining missing values
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [4]:
# Split into features (X) and target (y)
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Split data into training and test sets (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Optional: Scale the data for better model performance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Check the shape of the data
print(f'Training set shape: {X_train.shape}')
print(f'Test set shape: {X_test.shape}')

Training set shape: (537, 8)
Test set shape: (231, 8)

In [5]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [6]:
# Create a study object and optimize the objective function
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2026-08-09 08:44:55,373] A new study created in memory with name: no-name-ed46456a-1403-43af-a8d4-0dd70a513201
[I 2026-08-09 08:44:56,903] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 168, 'max_depth': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-08-09 08:44:58,199] Trial 1 finished with value: 0.756052141527002 and parameters: {'n_estimators': 120, 'max_depth': 3}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-08-09 08:45:00,236] Trial 2 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 154, 'max_depth': 11}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-08-09 08:45:02,249] Trial 3 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 103, 'max_depth': 17}. Best is trial 3 with value: 0.7746741154562384.
[I 2026-08-09 08:45:04,608] Trial 4 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 192, 'max_depth': 10}. Best is trial 3 with value: 0.7746741154562384.
[I 2026-08-09 08:45:07,148] Trial 5 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 188, 'max_depth': 4}. Best is trial 3 with value: 0.7746741154562384.
[I 2026-08-09 08:45:08,463] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 88, 'max_depth': 20}. Best is trial 3 with value: 0.7746741154562384.
[I 2026-08-09 08:45:12,927] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 183, 'max_depth': 13}. Best is trial 3 with value: 0.7746741154562384.
[I 2026-08-09 08:45:15,325] Trial 8 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 188, 'max_depth': 16}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-08-09 08:45:16,340] Trial 9 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 87, 'max_depth': 8}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-08-09 08:45:17,111] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 16}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-08-09 08:45:18,676] Trial 11 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 131, 'max_depth': 17}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-08-09 08:45:20,484] Trial 12 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 139, 'max_depth': 16}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-08-09 08:45:21,572] Trial 13 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 135, 'max_depth': 20}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-08-09 08:45:22,487] Trial 14 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 161, 'max_depth': 14}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-08-09 08:45:23,039] Trial 15 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 62, 'max_depth': 18}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-08-09 08:45:24,153] Trial 16 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 128, 'max_depth': 14}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-08-09 08:45:25,745] Trial 17 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 199, 'max_depth': 18}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-08-09 08:45:26,319] Trial 18 finished with value: 0.7821229050279329 and parameters: {'n_estimators': 104, 'max_depth': 12}. Best is trial 18 with value: 0.7821229050279329.
[I 2026-08-09 08:45:26,905] Trial 19 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 110, 'max_depth': 7}. Best is trial 18 with value: 0.7821229050279329.
[I 2026-08-09 08:45:27,420] Trial 20 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 94, 'max_depth': 11}. Best is trial 18 with value: 0.7821229050279329.
[I 2026-08-09 08:45:28,213] Trial 21 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 144, 'max_depth': 13}. Best is trial 18 with value: 0.7821229050279329.
[I 2026-08-09 08:45:28,629] Trial 22 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 71, 'max_depth': 15}. Best is trial 18 with value: 0.7821229050279329.
[I 2026-08-09 08:45:29,568] Trial 23 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 171, 'max_depth': 18}. Best is trial 18 with value: 0.7821229050279329.
[I 2026-08-09 08:45:30,231] Trial 24 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 118, 'max_depth': 12}. Best is trial 18 with value: 0.7821229050279329.
[I 2026-08-09 08:45:30,657] Trial 25 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 74, 'max_depth': 9}. Best is trial 18 with value: 0.7821229050279329.
[I 2026-08-09 08:45:31,522] Trial 26 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 153, 'max_depth': 15}. Best is trial 18 with value: 0.7821229050279329.
[I 2026-08-09 08:45:32,116] Trial 27 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 106, 'max_depth': 19}. Best is trial 18 with value: 0.7821229050279329.
[I 2026-08-09 08:45:32,809] Trial 28 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 125, 'max_depth': 16}. Best is trial 18 with value: 0.7821229050279329.
[I 2026-08-09 08:45:33,489] Trial 29 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 125, 'max_depth': 13}. Best is trial 18 with value: 0.7821229050279329.
[I 2026-08-09 08:45:34,003] Trial 30 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 96, 'max_depth': 6}. Best is trial 18 with value: 0.7821229050279329.
[I 2026-08-09 08:45:34,638] Trial 31 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 115, 'max_depth': 16}. Best is trial 18 with value: 0.7821229050279329.
[I 2026-08-09 08:45:35,275] Trial 32 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 113, 'max_depth': 17}. Best is trial 18 with value: 0.7821229050279329.
[I 2026-08-09 08:45:36,318] Trial 33 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 130, 'max_depth': 15}. Best is trial 18 with value: 0.7821229050279329.
[I 2026-08-09 08:45:37,599] Trial 34 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 146, 'max_depth': 17}. Best is trial 18 with value: 0.7821229050279329.
[I 2026-08-09 08:45:38,603] Trial 35 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 118, 'max_depth': 11}. Best is trial 18 with value: 0.7821229050279329.
[I 2026-08-09 08:45:39,163] Trial 36 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 99, 'max_depth': 19}. Best is trial 18 with value: 0.7821229050279329.
[I 2026-08-09 08:45:39,841] Trial 37 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 123, 'max_depth': 14}. Best is trial 18 with value: 0.7821229050279329.
[I 2026-08-09 08:45:40,492] Trial 38 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 135, 'max_depth': 3}. Best is trial 18 with value: 0.7821229050279329.
[I 2026-08-09 08:45:40,968] Trial 39 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 86, 'max_depth': 12}. Best is trial 18 with value: 0.7821229050279329.
[I 2026-08-09 08:45:41,601] Trial 40 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 112, 'max_depth': 17}. Best is trial 18 with value: 0.7821229050279329.
[I 2026-08-09 08:45:42,573] Trial 41 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 176, 'max_depth': 16}. Best is trial 18 with value: 0.7821229050279329.
[I 2026-08-09 08:45:43,471] Trial 42 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 163, 'max_depth': 16}. Best is trial 18 with value: 0.7821229050279329.
[I 2026-08-09 08:45:44,313] Trial 43 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 153, 'max_depth': 19}. Best is trial 18 with value: 0.7821229050279329.
[I 2026-08-09 08:45:44,886] Trial 44 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 104, 'max_depth': 15}. Best is trial 18 with value: 0.7821229050279329.
[I 2026-08-09 08:45:45,370] Trial 45 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 85, 'max_depth': 17}. Best is trial 18 with value: 0.7821229050279329.
[I 2026-08-09 08:45:46,377] Trial 46 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 186, 'max_depth': 9}. Best is trial 18 with value: 0.7821229050279329.
[I 2026-08-09 08:45:47,148] Trial 47 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 141, 'max_depth': 14}. Best is trial 18 with value: 0.7821229050279329.
[I 2026-08-09 08:45:47,889] Trial 48 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 131, 'max_depth': 20}. Best is trial 18 with value: 0.7821229050279329.
[I 2026-08-09 08:45:48,594] Trial 49 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 118, 'max_depth': 16}. Best is trial 18 with value: 0.7821229050279329.

In [7]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7821229050279329
Best hyperparameters: {'n_estimators': 104, 'max_depth': 12}

In [8]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.76

## Samplers in Optuna

In [9]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [10]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2026-08-09 08:45:48,989] A new study created in memory with name: no-name-ac40986d-1d74-48dc-97b4-0077d8c0cf29
[I 2026-08-09 08:45:49,468] Trial 0 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 51, 'max_depth': 8}. Best is trial 0 with value: 0.7709497206703911.
[I 2026-08-09 08:45:50,183] Trial 1 finished with value: 0.7597765363128492 and parameters: {'n_estimators': 82, 'max_depth': 10}. Best is trial 0 with value: 0.7709497206703911.
[I 2026-08-09 08:45:51,505] Trial 2 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 149, 'max_depth': 11}. Best is trial 0 with value: 0.7709497206703911.
[I 2026-08-09 08:45:51,841] Trial 3 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 56, 'max_depth': 12}. Best is trial 0 with value: 0.7709497206703911.
[I 2026-08-09 08:45:52,780] Trial 4 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 171, 'max_depth': 18}. Best is trial 4 with value: 0.7728119180633147.
[I 2026-08-09 08:45:53,492] Trial 5 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 131, 'max_depth': 16}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:45:54,026] Trial 6 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 95, 'max_depth': 16}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:45:54,596] Trial 7 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 104, 'max_depth': 15}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:45:55,606] Trial 8 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 184, 'max_depth': 20}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:45:56,114] Trial 9 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 92, 'max_depth': 8}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:45:56,955] Trial 10 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 176, 'max_depth': 3}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:45:57,268] Trial 11 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 56, 'max_depth': 20}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:45:58,169] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 165, 'max_depth': 18}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:45:59,017] Trial 13 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 154, 'max_depth': 17}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:45:59,794] Trial 14 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 143, 'max_depth': 10}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:46:00,739] Trial 15 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 175, 'max_depth': 14}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:46:01,671] Trial 16 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 159, 'max_depth': 13}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:46:03,211] Trial 17 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 180, 'max_depth': 8}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:46:03,724] Trial 18 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 62, 'max_depth': 4}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:46:04,819] Trial 19 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 141, 'max_depth': 17}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:46:05,875] Trial 20 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 195, 'max_depth': 10}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:46:06,202] Trial 21 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 56, 'max_depth': 10}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:46:07,137] Trial 22 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 174, 'max_depth': 19}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:46:07,671] Trial 23 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 94, 'max_depth': 17}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:46:08,119] Trial 24 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 88, 'max_depth': 5}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:46:09,038] Trial 25 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 167, 'max_depth': 19}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:46:09,819] Trial 26 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 142, 'max_depth': 10}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:46:10,571] Trial 27 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 135, 'max_depth': 14}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:46:11,253] Trial 28 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 127, 'max_depth': 9}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:46:12,065] Trial 29 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 147, 'max_depth': 16}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:46:12,711] Trial 30 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 116, 'max_depth': 10}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:46:13,180] Trial 31 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 85, 'max_depth': 11}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:46:14,067] Trial 32 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 183, 'max_depth': 4}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:46:14,931] Trial 33 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 129, 'max_depth': 11}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:46:15,563] Trial 34 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 71, 'max_depth': 12}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:46:17,218] Trial 35 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 190, 'max_depth': 14}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:46:18,217] Trial 36 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 100, 'max_depth': 8}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:46:18,828] Trial 37 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 99, 'max_depth': 3}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:46:19,803] Trial 38 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 93, 'max_depth': 16}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:46:21,238] Trial 39 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 199, 'max_depth': 6}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:46:22,101] Trial 40 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 157, 'max_depth': 17}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:46:22,784] Trial 41 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 124, 'max_depth': 9}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:46:23,351] Trial 42 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 110, 'max_depth': 6}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:46:23,844] Trial 43 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 88, 'max_depth': 10}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:46:24,442] Trial 44 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 111, 'max_depth': 9}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:46:25,012] Trial 45 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 102, 'max_depth': 10}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:46:25,793] Trial 46 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 145, 'max_depth': 14}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:46:26,170] Trial 47 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 65, 'max_depth': 12}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:46:26,825] Trial 48 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 122, 'max_depth': 10}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-08-09 08:46:27,797] Trial 49 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 166, 'max_depth': 7}. Best is trial 5 with value: 0.7783985102420856.

In [11]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7783985102420856
Best hyperparameters: {'n_estimators': 131, 'max_depth': 16}

In [12]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

In [13]:
search_space = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [5, 10, 15, 20]
}

In [14]:
# Create a study and optimize it using GridSampler
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.GridSampler(search_space))
study.optimize(objective)

[I 2026-08-09 08:46:28,266] A new study created in memory with name: no-name-52da9c23-d6c6-4cd5-a34c-bfd15da4dc11
[I 2026-08-09 08:46:29,082] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-08-09 08:46:30,396] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-08-09 08:46:30,774] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-08-09 08:46:31,333] Trial 3 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-08-09 08:46:31,896] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-08-09 08:46:32,178] Trial 5 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-08-09 08:46:32,940] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-08-09 08:46:33,769] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-08-09 08:46:34,592] Trial 8 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-08-09 08:46:35,670] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-08-09 08:46:36,755] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-08-09 08:46:37,845] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-08-09 08:46:38,853] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-08-09 08:46:39,109] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-08-09 08:46:39,665] Trial 14 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-08-09 08:46:39,946] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 13 with value: 0.7746741154562384.

In [15]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7746741154562384
Best hyperparameters: {'n_estimators': 50, 'max_depth': 5}

In [16]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

## Optuna Visualizations

In [17]:
# For visualizations
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

In [18]:
# 1. Optimization History
plot_optimization_history(study).show()

In [19]:
# 2. Parallel Coordinates Plot
plot_parallel_coordinate(study).show()

In [20]:
# 3. Slice Plot
plot_slice(study).show()

In [21]:
# 4. Contour Plot
plot_contour(study).show()

In [22]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

## Optimizing Multiple ML Models

In [23]:
# Importing the required libraries
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [24]:
# Define the objective function for Optuna
def objective(trial):
    # Choose the algorithm to tune
    classifier_name = trial.suggest_categorical('classifier', ['SVM', 'RandomForest', 'GradientBoosting'])

    if classifier_name == 'SVM':
        # SVM hyperparameters
        c = trial.suggest_float('C', 0.1, 100, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

        model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

    elif classifier_name == 'RandomForest':
        # Random Forest hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )

    elif classifier_name == 'GradientBoosting':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )

    # Perform cross-validation and return the mean accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

In [25]:
# Create a study and optimize it using CmaEsSampler
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2026-08-09 08:46:43,845] A new study created in memory with name: no-name-79871ed6-059c-4340-8708-f841a3575e26
[I 2026-08-09 08:46:43,883] Trial 0 finished with value: 0.7597765363128491 and parameters: {'classifier': 'SVM', 'C': 0.31719514166169915, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 0 with value: 0.7597765363128491.
[I 2026-08-09 08:46:45,283] Trial 1 finished with value: 0.7597765363128491 and parameters: {'classifier': 'RandomForest', 'n_estimators': 280, 'max_depth': 19, 'min_samples_split': 4, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 0 with value: 0.7597765363128491.
[I 2026-08-09 08:46:45,313] Trial 2 finished with value: 0.7672253258845437 and parameters: {'classifier': 'SVM', 'C': 0.5685879550097894, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 2 with value: 0.7672253258845437.
[I 2026-08-09 08:46:45,771] Trial 3 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 83, 'max_depth': 15, 'min_samples_split': 9, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 3 with value: 0.7728119180633147.
[I 2026-08-09 08:46:51,181] Trial 4 finished with value: 0.7411545623836128 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 287, 'learning_rate': 0.01322260806013891, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 3}. Best is trial 3 with value: 0.7728119180633147.
[I 2026-08-09 08:46:52,210] Trial 5 finished with value: 0.7635009310986964 and parameters: {'classifier': 'RandomForest', 'n_estimators': 207, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 3 with value: 0.7728119180633147.
[I 2026-08-09 08:46:54,246] Trial 6 finished with value: 0.7430167597765363 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 225, 'learning_rate': 0.04778224738504189, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 1}. Best is trial 3 with value: 0.7728119180633147.
[I 2026-08-09 08:46:55,251] Trial 7 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 143, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 3 with value: 0.7728119180633147.
[I 2026-08-09 08:46:56,049] Trial 8 finished with value: 0.7765363128491621 and parameters: {'classifier': 'RandomForest', 'n_estimators': 122, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 8 with value: 0.7765363128491621.
[I 2026-08-09 08:46:56,088] Trial 9 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.46754754480098615, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 9 with value: 0.7839851024208566.
[I 2026-08-09 08:46:56,560] Trial 10 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 50.92874501369328, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7858472998137801.
[I 2026-08-09 08:46:56,965] Trial 11 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 93.06805738904085, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7858472998137801.
[I 2026-08-09 08:46:57,356] Trial 12 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 98.36906775938834, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7858472998137801.
[I 2026-08-09 08:46:57,578] Trial 13 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 68.7766175698828, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7858472998137801.
[I 2026-08-09 08:46:57,621] Trial 14 finished with value: 0.7076350093109869 and parameters: {'classifier': 'SVM', 'C': 12.089812788977511, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 10 with value: 0.7858472998137801.
[I 2026-08-09 08:46:57,703] Trial 15 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 14.5143523967454, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7858472998137801.
[I 2026-08-09 08:46:57,798] Trial 16 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 18.2391387862596, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7858472998137801.
[I 2026-08-09 08:46:58,703] Trial 17 finished with value: 0.7281191806331471 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 59, 'learning_rate': 0.2648246803160321, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 6}. Best is trial 10 with value: 0.7858472998137801.
[I 2026-08-09 08:46:58,748] Trial 18 finished with value: 0.7374301675977653 and parameters: {'classifier': 'SVM', 'C': 36.592851297798475, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 10 with value: 0.7858472998137801.
[I 2026-08-09 08:46:58,782] Trial 19 finished with value: 0.696461824953445 and parameters: {'classifier': 'SVM', 'C': 7.203769214335346, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 10 with value: 0.7858472998137801.
[I 2026-08-09 08:47:00,788] Trial 20 finished with value: 0.7411545623836128 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 182, 'learning_rate': 0.27116808642203843, 'max_depth': 13, 'min_samples_split': 8, 'min_samples_leaf': 10}. Best is trial 10 with value: 0.7858472998137801.
[I 2026-08-09 08:47:01,095] Trial 21 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 94.05586940388832, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7858472998137801.
[I 2026-08-09 08:47:01,460] Trial 22 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 99.04648056600278, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7858472998137801.
[I 2026-08-09 08:47:01,664] Trial 23 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 36.26228002680322, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7858472998137801.
[I 2026-08-09 08:47:01,743] Trial 24 finished with value: 0.702048417132216 and parameters: {'classifier': 'SVM', 'C': 40.061755545992135, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 10 with value: 0.7858472998137801.
[I 2026-08-09 08:47:01,795] Trial 25 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 5.13386315859303, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7858472998137801.
[I 2026-08-09 08:47:01,965] Trial 26 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 39.33529391930526, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7858472998137801.
[I 2026-08-09 08:47:02,008] Trial 27 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 3.5156505081301765, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7858472998137801.
[I 2026-08-09 08:47:03,243] Trial 28 finished with value: 0.7635009310986964 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 235, 'learning_rate': 0.058847208108545795, 'max_depth': 3, 'min_samples_split': 7, 'min_samples_leaf': 5}. Best is trial 10 with value: 0.7858472998137801.
[I 2026-08-09 08:47:03,336] Trial 29 finished with value: 0.690875232774674 and parameters: {'classifier': 'SVM', 'C': 53.43520561207113, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 10 with value: 0.7858472998137801.
[I 2026-08-09 08:47:03,377] Trial 30 finished with value: 0.7411545623836128 and parameters: {'classifier': 'SVM', 'C': 20.879612764368687, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 10 with value: 0.7858472998137801.
[I 2026-08-09 08:47:03,691] Trial 31 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 85.94374486435127, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7858472998137801.
[I 2026-08-09 08:47:03,907] Trial 32 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 61.50885796739768, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7858472998137801.
[I 2026-08-09 08:47:04,023] Trial 33 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 24.899520700859856, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7858472998137801.
[I 2026-08-09 08:47:04,243] Trial 34 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 63.160413438409535, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7858472998137801.
[I 2026-08-09 08:47:04,882] Trial 35 finished with value: 0.7616387337057727 and parameters: {'classifier': 'RandomForest', 'n_estimators': 132, 'max_depth': 16, 'min_samples_split': 2, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 10 with value: 0.7858472998137801.
[I 2026-08-09 08:47:04,914] Trial 36 finished with value: 0.6852886405959032 and parameters: {'classifier': 'SVM', 'C': 95.19773517871262, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 10 with value: 0.7858472998137801.
[I 2026-08-09 08:47:05,032] Trial 37 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 26.239258454197007, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7858472998137801.
[I 2026-08-09 08:47:05,762] Trial 38 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 169, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 10 with value: 0.7858472998137801.
[I 2026-08-09 08:47:09,913] Trial 39 finished with value: 0.7672253258845437 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 255, 'learning_rate': 0.011712306939660804, 'max_depth': 16, 'min_samples_split': 4, 'min_samples_leaf': 7}. Best is trial 10 with value: 0.7858472998137801.
[I 2026-08-09 08:47:10,133] Trial 40 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 56.419404469696644, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7858472998137801.
[I 2026-08-09 08:47:10,161] Trial 41 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1080296038409539, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 41 with value: 0.7877094972067038.
[I 2026-08-09 08:47:10,192] Trial 42 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.0000580001315196, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 41 with value: 0.7877094972067038.
[I 2026-08-09 08:47:10,227] Trial 43 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.75436628511031, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 41 with value: 0.7877094972067038.
[I 2026-08-09 08:47:10,731] Trial 44 finished with value: 0.7597765363128491 and parameters: {'classifier': 'RandomForest', 'n_estimators': 103, 'max_depth': 3, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 41 with value: 0.7877094972067038.
[I 2026-08-09 08:47:10,774] Trial 45 finished with value: 0.7672253258845437 and parameters: {'classifier': 'SVM', 'C': 0.11305795924090004, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 41 with value: 0.7877094972067038.
[I 2026-08-09 08:47:10,811] Trial 46 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1505348791411123, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 46 with value: 0.7895716945996275.
[I 2026-08-09 08:47:10,846] Trial 47 finished with value: 0.7262569832402234 and parameters: {'classifier': 'SVM', 'C': 0.11022788793080976, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 46 with value: 0.7895716945996275.
[I 2026-08-09 08:47:10,875] Trial 48 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2020390350965411, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 46 with value: 0.7895716945996275.
[I 2026-08-09 08:47:11,159] Trial 49 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 59, 'max_depth': 18, 'min_samples_split': 7, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 46 with value: 0.7895716945996275.
[I 2026-08-09 08:47:14,368] Trial 50 finished with value: 0.750465549348231 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 171, 'learning_rate': 0.06875022325365364, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 8}. Best is trial 46 with value: 0.7895716945996275.
[I 2026-08-09 08:47:14,418] Trial 51 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.19354481987211616, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 46 with value: 0.7895716945996275.
[I 2026-08-09 08:47:14,469] Trial 52 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.18211370910683305, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 46 with value: 0.7895716945996275.
[I 2026-08-09 08:47:14,527] Trial 53 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2032798122813923, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 46 with value: 0.7895716945996275.
[I 2026-08-09 08:47:14,575] Trial 54 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.247099647997033, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 46 with value: 0.7895716945996275.
[I 2026-08-09 08:47:14,639] Trial 55 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.4367662393273231, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 46 with value: 0.7895716945996275.
[I 2026-08-09 08:47:14,715] Trial 56 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.18032364425363387, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 46 with value: 0.7895716945996275.
[I 2026-08-09 08:47:14,772] Trial 57 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.8941038963381873, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 46 with value: 0.7895716945996275.
[I 2026-08-09 08:47:14,862] Trial 58 finished with value: 0.7132216014897579 and parameters: {'classifier': 'SVM', 'C': 0.15089795292913846, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 46 with value: 0.7895716945996275.
[I 2026-08-09 08:47:14,919] Trial 59 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.34087299541775407, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 46 with value: 0.7895716945996275.
[I 2026-08-09 08:47:14,986] Trial 60 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.3018845655522521, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 46 with value: 0.7895716945996275.
[I 2026-08-09 08:47:15,075] Trial 61 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.17369283375597516, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 46 with value: 0.7895716945996275.
[I 2026-08-09 08:47:15,177] Trial 62 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1615937402279048, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 46 with value: 0.7895716945996275.
[I 2026-08-09 08:47:15,251] Trial 63 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1512270060329058, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 46 with value: 0.7895716945996275.
[I 2026-08-09 08:47:15,295] Trial 64 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13915589132388284, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 46 with value: 0.7895716945996275.
[I 2026-08-09 08:47:15,361] Trial 65 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 0.13236611741495075, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 46 with value: 0.7895716945996275.
[I 2026-08-09 08:47:24,527] Trial 66 finished with value: 0.7430167597765363 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 300, 'learning_rate': 0.027301905578143024, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 5}. Best is trial 46 with value: 0.7895716945996275.
[I 2026-08-09 08:47:24,563] Trial 67 finished with value: 0.7094972067039106 and parameters: {'classifier': 'SVM', 'C': 0.10090452774263113, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 46 with value: 0.7895716945996275.
[I 2026-08-09 08:47:24,600] Trial 68 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.286210426289489, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 46 with value: 0.7895716945996275.
[I 2026-08-09 08:47:24,634] Trial 69 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.4019727020450034, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 46 with value: 0.7895716945996275.
[I 2026-08-09 08:47:24,661] Trial 70 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1556178524281763, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 46 with value: 0.7895716945996275.
[I 2026-08-09 08:47:24,689] Trial 71 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.16958303209844502, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 46 with value: 0.7895716945996275.
[I 2026-08-09 08:47:24,717] Trial 72 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.21554335316617462, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 46 with value: 0.7895716945996275.
[I 2026-08-09 08:47:24,744] Trial 73 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13785547971887338, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 46 with value: 0.7895716945996275.
[I 2026-08-09 08:47:24,774] Trial 74 finished with value: 0.7094972067039106 and parameters: {'classifier': 'SVM', 'C': 0.12595577740019365, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 46 with value: 0.7895716945996275.
[I 2026-08-09 08:47:24,802] Trial 75 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2490967329875596, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 46 with value: 0.7895716945996275.
[I 2026-08-09 08:47:25,865] Trial 76 finished with value: 0.7672253258845437 and parameters: {'classifier': 'RandomForest', 'n_estimators': 199, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 46 with value: 0.7895716945996275.
[I 2026-08-09 08:47:25,895] Trial 77 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1364595240834583, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 46 with value: 0.7895716945996275.
[I 2026-08-09 08:47:25,923] Trial 78 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.140410837004284, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 46 with value: 0.7895716945996275.
[I 2026-08-09 08:47:28,849] Trial 79 finished with value: 0.7243947858472998 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 256, 'learning_rate': 0.13398514827879318, 'max_depth': 13, 'min_samples_split': 3, 'min_samples_leaf': 9}. Best is trial 46 with value: 0.7895716945996275.
[I 2026-08-09 08:47:28,878] Trial 80 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12884891692977904, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 46 with value: 0.7895716945996275.
[I 2026-08-09 08:47:28,906] Trial 81 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12852103950479615, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 46 with value: 0.7895716945996275.

In [26]:
# Retrieve the best trial
best_trial = study.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'classifier': 'SVM', 'C': 0.1505348791411123, 'kernel': 'linear', 'gamma': 'auto'}
Best trial accuracy: 0.7895716945996275

In [27]:
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_C,params_bootstrap,params_classifier,params_gamma,params_kernel,params_learning_rate,params_max_depth,params_min_samples_leaf,params_min_samples_split,params_n_estimators,state
0,0,0.759777,2026-08-09 08:46:43.847430,2026-08-09 08:46:43.883380,0 days 00:00:00.035950,0.317195,NaN,SVM,scale,sigmoid,NaN,NaN,NaN,NaN,NaN,COMPLETE
1,1,0.759777,2026-08-09 08:46:43.884224,2026-08-09 08:46:45.283329,0 days 00:00:01.399105,NaN,True,RandomForest,NaN,NaN,NaN,19.0,7.0,4.0,280.0,COMPLETE
2,2,0.767225,2026-08-09 08:46:45.284389,2026-08-09 08:46:45.313851,0 days 00:00:00.029462,0.568588,NaN,SVM,scale,rbf,NaN,NaN,NaN,NaN,NaN,COMPLETE
3,3,0.772812,2026-08-09 08:46:45.314720,2026-08-09 08:46:45.771269,0 days 00:00:00.456549,NaN,True,RandomForest,NaN,NaN,NaN,15.0,4.0,9.0,83.0,COMPLETE
4,4,0.741155,2026-08-09 08:46:45.772256,2026-08-09 08:46:51.181127,0 days 00:00:05.408871,NaN,NaN,GradientBoosting,NaN,NaN,0.013223,11.0,3.0,6.0,287.0,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0.789572,2026-08-09 08:47:29.723688,2026-08-09 08:47:29.752854,0 days 00:00:00.029166,0.122994,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
96,96,0.715084,2026-08-09 08:47:29.753974,2026-08-09 08:47:29.793060,0 days 00:00:00.039086,0.157926,NaN,SVM,scale,poly,NaN,NaN,NaN,NaN,NaN,COMPLETE
97,97,0.785847,2026-08-09 08:47:29.793943,2026-08-09 08:47:29.822657,0 days 00:00:00.028714,0.217363,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
98,98,0.789572,2026-08-09 08:47:29.823439,2026-08-09 08:47:29.849933,0 days 00:00:00.026494,0.119205,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
99,99,0.739292,2026-08-09 08:47:29.850747,2026-08-09 08:47:32.839357,0 days 00:00:02.988610,NaN,NaN,GradientBoosting,NaN,NaN,0.027656,17.0,2.0,9.0,151.0,COMPLETE

In [28]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 79
RandomForest        11
GradientBoosting    10
Name: count, dtype: int64

In [29]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting    0.744134
RandomForest        0.766379
SVM                 0.773448
Name: value, dtype: float64

In [30]:
# 1. Optimization History
plot_optimization_history(study).show()

In [31]:
# 3. Slice Plot
plot_slice(study).show()

In [32]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()